enabled: true
fullnameOverride: ''
replicaCount: 1
image:
  repository: ''
  tag: latest
  pullPolicy: IfNotPresent
service:
  enabled: true
  type: ClusterIP
  port: 9090
  targetPort: 9090
env: []
command: []
args: []
resources: {}
podAnnotations: {}
extraVolumes: []
extraVolumeMounts: []
sharedStorage:
  subPaths:
    gdiConfig: vector/qwc-storage/solr/configsets/gdi
    solrData: vector/qwc-storage/solr/data
configMap:
  enabled: false
  data: {}
ingress:
  enabled: false
  className: ''
  host: ''
  path: /
  pathType: Prefix
