{{- if .Values.global.jwt.createSecret }}
{{- $name := "qwc-jwt" }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $jwt := "" }}
{{- if .Values.global.jwt.secretKey }}
{{- $jwt = .Values.global.jwt.secretKey | b64enc }}
{{- else if and $existing (hasKey $existing.data "JWT_SECRET_KEY") }}
{{- $jwt = index $existing.data "JWT_SECRET_KEY" }}
{{- else }}
{{- $jwt = randAlphaNum 64 | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ $jwt | quote }}
{{- end }}
