{{- if and .Values.enabled .Values.qgisAuthFiles.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "qwc-qgis-server.qgisAuthFiles.secretName is required when qgisAuthFiles.enabled=true" .Values.qgisAuthFiles.secretName }}
type: Opaque
data:
  {{ required "qwc-qgis-server.qgisAuthFiles.dbKey is required when qgisAuthFiles.enabled=true" .Values.qgisAuthFiles.dbKey }}: {{ .Files.Get (required "qwc-qgis-server.qgisAuthFiles.dbFilePath is required when qgisAuthFiles.enabled=true" .Values.qgisAuthFiles.dbFilePath) | b64enc }}
  {{ required "qwc-qgis-server.qgisAuthFiles.txtKey is required when qgisAuthFiles.enabled=true" .Values.qgisAuthFiles.txtKey }}: {{ required "qwc-qgis-server.qgisAuthFiles.masterKey is required when qgisAuthFiles.enabled=true" .Values.qgisAuthFiles.masterKey | b64enc }}
{{- end }}
